name: code
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_svg: ^1.1.6
  retrofit: ^3.3.1
  analyzer: ^5.4.0
  dio: ^4.0.6
  json_serializable: ^6.6.1
  dartz: ^0.10.1
  shared_preferences: ^2.0.17
  pretty_dio_logger: ^1.2.0-beta-1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/images/



  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
